ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: "paso.tolit-dev.k8s.sanger.ac.uk"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - "paso.tolit-dev.k8s.sanger.ac.uk"
      secretName: default-ingress-tls-secret

database:
  host: software-tracker-test-db.internal.sanger.ac.uk
  port:  3350
  roUser: tol_ro
  roPassword: ""
  rwUser: tol
  rwPassword: ""
