ingress:
  enabled: true
  hosts:
    - host: "paso.tol.sanger.ac.uk"
      paths:
        - path: /
          pathType: Prefix
  tls: []

database:
  host: software-tracker-db-tol-mysql.tol-software-tracking.svc.cluster.local
  port:  3306 # 30098
  roUser: tol
  roPassword: ""
  rwUser: toladmin
  rwPassword: ""
