ingress:
  enabled: true
  hosts:
    - host: "paso.tol.sanger.ac.uk"
      paths:
        - path: /
          pathType: Prefix
  tls: []

database:
  host: software-tracker-prod-db.internal.sanger.ac.uk
  port:  3351
  roUser: tol_ro
  roPassword: ""
  rwUser: tol
  rwPassword: ""
