ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: "paso.tol-dev.sanger.ac.uk"
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

database:
  host: software-tracker-test-db.internal.sanger.ac.uk
  port:  3350
  roUser: tol_ro
  roPassword: ""
  rwUser: tol
  rwPassword: ""
